### ISSUE TITLE
v19.2.4 checklist

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/barinsta#1567]
## Rewrites

- [x] Story ViewModel → close #537 and #1554 
- [ ] #1542 

## Bugs

- [x] #1568
- [x] #1570
- [ ] `reel_share` item layout
- [x] #1529 
- [x] #1499 (mitigate by writing default value)
- [x] #1467 (mitigate by AlertDialog)
- [x] F-Droid: put old placeholder images
- [x] try-catch for GraphQL user parsing
