### ISSUE TITLE
Todo before v19.1.0 full release

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/barinsta#688]
- [ ] Profile DM button
- [ ] DM mark-as-read
- [x] Story mark-as-read
- [x] PostRecycler variable height view sidecar bug => https://t.me/grabber_app/17029
- [x] #689 
- [x] #463 just the typeface
- [x] `R.string.error_loading_location`
- [x] `Attempt to invoke virtual method 'java.lang.String awais.instagrabber.webservices.StoriesService$ArchiveFetchResponse.getNextCursor()' on a null object reference`
- [x] #748
- [x] Greek and Basque
- [x] Contributors

* ~~Menubar red bubble~~ not testable at my perspective anymore

delayed:

* Suggested users per user
* Ignore suggested user & show AlertDialog with algorithm name

**Comment by austinhuang0131** [comment]
https://git.sr.ht/~cadence/bibliogram/commit/7fd90bce54235b90a625182bfc232fcde928e98a

**Comment by austinhuang0131** [comment]
i think #753 is dealing with the other two
