### ISSUE TITLE
Todo before v19.1.1

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/barinsta#897]
No more new features should be worked on for this version.

- [x] Fix #850 
- [ ] Patrol small bugs
- [x] Fix filenames for downloading DM images
- [ ] Write information about nightly builds

#840 can wait, or we can merge as-is.

Preferably to be done before April 3 since #813 is too urgent

**Comment by ammargitham** [comment]
The release will require #900 since the version names have changed
